version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 60

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: always
    depends_on: 
      postgres:
        condition: service_healthy
    ports:
      - '${ADMINER_HOST_PORT:-8081}:8080'
volumes: 
  pgdata:
